### ISSUE TITLE
数据结构第六章未满分

### ISSUE THREAD

**Issue by colinaaa** [colinaaa/icourse-answer#1]
在[第六章](https://www.icourse163.org/learn/HUST-1001907004?tid=1206786246&from=study#/learn/quiz?id=1220071010)中，由于题库增大，导致出现**新的题目**与**题目顺序改变**，从而未满分

**Comment by colinaaa** [comment]
据观察，只有判断题会有新题

**Comment by ManiaciaChao** [comment]
In fact, chapter 8 and 10 also introduce new questions, which made me unable to get full scores.

**Comment by colinaaa** [comment]
> which made me unable to get full scores.

Congratulations! 🎉
